import time
import numpy as np
from flcore.clients.clienttspv4 import clientTSPv4
from flcore.servers.serverbase import Server
from flcore.clients.clientbase import load_item, save_item
from utils.data_utils import read_client_data
from threading import Thread
from collections import defaultdict
import json
import copy
from tqdm import tqdm
import clip
from flcore.trainmodel.clip_base import TextEncoder_server
from flcore.trainmodel.bert_base import TextEncoder_server_bert
import torch
import torch.nn.functional as F
import os

'''
The main difference between FedTSPv4 and FedTSPv3 is FedTSPv4 1) allow personalized/global/frozen classifier; 2) detailed text prompt generated by LLM.
'''
class FedTSPv4(Server):
    def __init__(self, args, times):
        super().__init__(args, times)

        # set logger
        if 'main.py' in self.caller_script:
            logger_path = (f'../logs/{args.dataset}/{args.model_family}/{args.algorithm}/gr{args.global_rounds}_'
                        f'ep{args.local_epochs}_bs{args.batch_size}_nc{args.num_clients}/lr({args.local_learning_rate}_{args.prompt_lr})_'
                        f'lamda(t{args.lamda})_cls{args.p_classifier}_prompt(CSC{args.CSC}_len{args.len_prompt}_random{args.prompt_random_init})_'
                        f'EMA{args.EMA_alpha}_promptep{args.prompt_epoch}_{args.server_model}_seed{args.seed}/')
        else:
            logger_path = (f'../visualization_logs/{args.dataset}/{args.model_family}/{args.algorithm}/gr{args.global_rounds}_'
                        f'ep{args.local_epochs}_bs{args.batch_size}_nc{args.num_clients}/lr({args.local_learning_rate}_{args.prompt_lr})_'
                        f'lamda(t{args.lamda})_cls{args.p_classifier}_prompt(CSC{args.CSC}_len{args.len_prompt}_random{args.prompt_random_init})_'
                        f'EMA{args.EMA_alpha}_promptep{args.prompt_epoch}_{args.server_model}_seed{args.seed}/')
        self.set_loggers(logger_path)
        self.args.logger = self.logger
        self.args.tensorboardLogger = self.tensorboardLogger
        if 'main.py' in self.caller_script:
            self.final_log_path = f'../logs/{args.dataset}/{args.model_family}/{args.algorithm}/gr{args.global_rounds}_ep{args.local_epochs}_bs{args.batch_size}_nc{args.num_clients}/summary_{args.server_model}.txt'
        else:
            self.final_log_path = f'../visualization_logs/{args.dataset}/{args.model_family}/{args.algorithm}/gr{args.global_rounds}_ep{args.local_epochs}_bs{args.batch_size}_nc{args.num_clients}/summary_{args.server_model}.txt'


        self.model_save_path = (f'../save/{args.dataset}/{args.model_family}/{args.algorithm}/gr{args.global_rounds}_'
                                f'ep{args.local_epochs}_bs{args.batch_size}_nc{args.num_clients}/lamda(t{args.lamda})_cls{args.p_classifier}_'
                                f'prompt(CSC{args.CSC}_len{args.len_prompt}_random{args.prompt_random_init})_'
                                f'EMA{args.EMA_alpha}_promptep{args.prompt_epoch}_{args.server_model}_seed{args.seed}')

        self.plot_path = (f'../plot/{args.dataset}/{args.model_family}/{args.algorithm}/gr{args.global_rounds}_'
                                f'ep{args.local_epochs}_bs{args.batch_size}_nc{args.num_clients}/lamda(t{args.lamda})_cls{args.p_classifier}_'
                                f'prompt(CSC{args.CSC}_len{args.len_prompt}_random{args.prompt_random_init})_'
                                f'EMA{args.EMA_alpha}_promptep{args.prompt_epoch}_{args.server_model}_seed{args.seed}')

        # obtain the classes
        dataset_json_dir = f'../dataset/{args.dataset}/config.json'
        with open(dataset_json_dir, 'r') as f:
            data_config = json.load(f)
        self.args.classes = data_config['classes']

        # select slow clients
        self.set_slow_clients()
        self.set_clients(clientTSPv4)

        print(f"\nJoin ratio / total clients: {self.join_ratio} / {self.num_clients}")
        print("Finished creating server and clients.")

        # self.load_model()
        self.Budget = []
        self.num_classes = args.num_classes

        # load server model
        if args.server_model == 'clip':
            if not os.path.exists(self.args.clip_model_path):
                clip_model, _ = clip.load('ViT-B/32', device=torch.device("cpu"))
                torch.save(clip_model, self.args.clip_model_path)
            else:
                clip_model = torch.load(self.args.clip_model_path)
            clip_model.to(self.device)
            self.global_model = TextEncoder_server(self.args.classes, clip_model, self.args.len_prompt, self.args.CSC, self.args.prompt_random_init).to(self.device)
            for name, param in self.global_model.named_parameters():
                if 'prompt_learner' in name or 'logit_scale' in name:
                    param.requires_grad_(True)
                else:
                    param.requires_grad_(False)
        elif args.server_model == 'bert':
            self.global_model = TextEncoder_server_bert(self.args.classes, self.args.len_prompt, pretrained_model_name=args.bert_model_path, CSC=self.args.CSC, random_init=self.args.prompt_random_init).to(self.device)
            for name, param in self.global_model.named_parameters():
                if 'prompt_learner' in name or 'logit_scale' in name:
                    param.requires_grad_(True)
                else:
                    param.requires_grad_(False)


        self.prompt_lr = args.prompt_lr

        # for vision prototype alignment
        self.global_vision_protos = None

        # for text prorotype alignment
        self.global_text_protos = None

        self.global_classifier = None

        self.epoch = 0

    def train(self):
        for i in tqdm(range(self.global_rounds + 1)):
            s_t = time.time()
            self.selected_clients = self.select_clients()

            if i % self.eval_gap == 0:
                print(f"\n-------------Round number: {i}-------------")
                print("\nEvaluate heterogeneous models")
                self.logger.info(f"\n-------------Round number: {i}-------------")
                self.logger.info("\nEvaluate heterogeneous models")
                self.epoch = i
                self.evaluate()

            # self.global_text_protos = self.global_model.get_text_prototypes()
            new_global_text_protos = self.global_model.get_text_prototypes()
            if self.global_text_protos is None:
                self.global_text_protos = new_global_text_protos
            else:
                self.global_text_protos = self.args.EMA_alpha * self.global_text_protos + (1 - self.args.EMA_alpha) * new_global_text_protos
            self.send_parameters()

            print(f'Round {i}, local training starts.')
            self.logger.info(f'Round {i}, local training starts.')

            # client training
            for client in self.selected_clients:
                client.train()

            self.receive_ids()

            self.aggregate_parameters()

            # server training to optimize the text prompt
            if self.args.len_prompt > 0 and i % self.args.server_training_freq == 0:
                print(f'Rounds {i}, server training starts.')
                self.logger.info(f'Rounds {i}, server training starts.')
                prompts = self.global_model.prompt_learner
                old_prompts = copy.deepcopy(prompts)
                optimizer_prompts = torch.optim.SGD(prompts.parameters(), lr=self.prompt_lr)
                optimizer_logit_scale = torch.optim.SGD([self.global_model.logit_scale], lr=self.prompt_lr)
                for j in range(self.args.prompt_epoch):
                    clip_logits = self.global_model(self.global_vision_protos)
                    loss = F.cross_entropy(clip_logits, torch.tensor([i for i in range(self.num_classes)]).to(self.device))
                    optimizer_prompts.zero_grad()
                    optimizer_logit_scale.zero_grad()
                    loss.backward()
                    optimizer_prompts.step()
                    optimizer_logit_scale.step()
                    print(f'Prompt training epoch {j}, loss: {loss.item()}')
                    self.logger.info(f'Prompt training epoch {j}, loss: {loss.item()}')
                    print(f'logit_scale: {self.global_model.logit_scale.item()}')
                for param, old_param in zip(prompts.parameters(), old_prompts.parameters()):
                    param.data = self.args.prompt_EMA_alpha * old_param.data + (1 - self.args.prompt_EMA_alpha) * param.data




            self.Budget.append(time.time() - s_t)
            print('-' * 50, self.Budget[-1])

            if self.auto_break and self.check_done(acc_lss=[self.rs_test_acc], top_cnt=self.top_cnt):
                break

        hyperparameters = {
            'prompt_lr': self.prompt_lr,
            'text_lamda': self.args.lamda,
            'vision_lamda': self.args.vision_proto,
            'classifier': self.args.p_classifier,
            'prompt_len': self.args.len_prompt,
            'prompt_random_init': self.args.prompt_random_init,
            'EMA_alpha': self.args.EMA_alpha,
            'prompt_EMA_alpha': self.args.prompt_EMA_alpha,
            'prompt_epoch': self.args.prompt_epoch,
            'server_training_freq': self.args.server_training_freq,
            'seed': self.args.seed
        }
        results = {
            'Best accuracy': self.best_acc,
            'Best epoch': self.best_epoch,
        }
        self.log_experiment_results(self.final_log_path, hyperparameters, results)

        print("\nBest accuracy.")
        # self.print_(max(self.rs_test_acc), max(
        #     self.rs_train_acc), min(self.rs_train_loss))
        print(max(self.rs_test_acc))
        print(sum(self.Budget[1:]) / len(self.Budget[1:]))
        self.save_results()

    def aggregate_parameters(self):
        assert (len(self.uploaded_ids) > 0)

        # aggregate global classifier
        if self.args.p_classifier == 0:
            client = self.clients[self.uploaded_ids[0]]
            global_classifier = copy.deepcopy(client.model.head)
            for param in global_classifier.parameters():
                param.data.zero_()
            for w, cid in zip(self.uploaded_weights, self.uploaded_ids):
                client = self.clients[cid]
                client_classifier = copy.deepcopy(client.model.head)
                for server_param, client_param in zip(global_classifier.parameters(), client_classifier.parameters()):
                    server_param.data += client_param.data.clone() * w
            self.global_classifier = global_classifier
        else:
            self.global_classifier = None

        # aggregate global vision prototype
        print('Aggregate vision prototypes')
        uploaded_protos = []
        for client in self.selected_clients:
            protos = client.local_vision_proto
            uploaded_protos.append(protos)
        self.global_vision_protos = proto_aggregation(uploaded_protos)

    def send_parameters(self):
        assert (len(self.clients) > 0)

        for client in self.clients:
            start_time = time.time()

            client.set_parameters(self.global_classifier, self.global_vision_protos, self.global_text_protos)
            client.set_logit_scale(self.global_model.logit_scale)
            client.epoch = self.epoch

            client.send_time_cost['num_rounds'] += 1
            client.send_time_cost['total_cost'] += 2 * (time.time() - start_time)

    def save_model(self):
        if not os.path.exists(self.model_save_path):
            os.makedirs(self.model_save_path)
        # save server model
        torch.save(self.global_model, f'{self.model_save_path}/server_model.pth')

        # save client models
        for c in self.clients:
            c.save_model(save_dir=self.model_save_path)

    def load_model(self):
        if not os.path.exists(self.model_save_path):
            raise ValueError(f'No model to load: {self.model_save_path}')

        # load server model
        self.global_model = torch.load(f'{self.model_save_path}/server_model.pth').to(self.device)

        # load client models
        for c in self.clients:
            c.load_model(save_dir=self.model_save_path)

    def test_metrics(self):
        num_samples = []
        tot_correct = []
        tot_losses = []
        for c in self.clients:
            correct_num, test_num, total_loss = c.test_metrics()
            tot_correct.append(correct_num)
            # print(f'Client {c.id}: Test Acc: {correct_num * 1.0 / test_num}, Test Loss: {total_loss * 1.0 / test_num}')
            tot_losses.append(total_loss)
            num_samples.append(test_num)

        ids = [c.id for c in self.clients]

        return ids, num_samples, tot_correct, tot_losses

    def train_metrics(self):
        num_samples = []
        tot_correct = []
        tot_losses = []
        for c in self.clients:
            total_loss, train_num, correct_num = c.train_metrics()
            num_samples.append(train_num)
            tot_losses.append(total_loss)
            # print(f'Client {c.id}: Train Acc: {correct_num * 1.0 / train_num}, Train Loss: {total_loss * 1.0 / train_num}')
            tot_correct.append(correct_num)

        ids = [c.id for c in self.clients]

        return ids, num_samples, tot_correct, tot_losses

    # evaluate selected clients
    def evaluate(self, acc=None, loss=None):
        stats = self.test_metrics()
        stats_train = self.train_metrics()

        test_acc = sum(stats[2]) * 1.0 / sum(stats[1])
        test_loss = sum(stats[3]) * 1.0 / sum(stats[1])
        test_accs = [a / n for a, n in zip(stats[2], stats[1])]
        test_losses = [a / n for a, n in zip(stats[3], stats[1])]

        if test_acc >= self.best_acc:
            self.best_acc = test_acc
            self.best_epoch = self.epoch
            if self.args.save_model != 0:
                self.save_model()

        if acc == None:
            self.rs_test_acc.append(test_acc)
        else:
            acc.append(test_acc)

        train_acc = sum(stats_train[2]) * 1.0 / sum(stats_train[1])
        train_loss = sum(stats_train[3])*1.0 / sum(stats_train[1])
        train_accs = [a / n for a, n in zip(stats_train[2], stats_train[1])]
        train_losses = [a / n for a, n in zip(stats_train[3], stats_train[1])]

        # if loss == None:
        #     self.rs_train_loss.append(train_loss)
        # else:
        #     loss.append(train_loss)

        # print("Averaged Train Loss: {:.4f}".format(train_loss))

        print(f'Train acc per client:{train_accs}')
        print(f'Test acc per clients: {test_accs}')

        print("Averaged Train Accurancy: {:.4f}".format(train_acc), end=', ')
        print("Std Train Accurancy: {:.4f}".format(np.std(train_accs)), end=', ')
        print("Averaged Train Loss: {:.4f}".format(train_loss), end=', ')
        print("Std Train Loss: {:.4f}".format(np.std(train_losses)))

        print("Averaged Test Accurancy: {:.4f}".format(test_acc), end=', ')
        print("Std Test Accurancy: {:.4f}".format(np.std(test_accs)), end=', ')
        print("Averaged Test Loss: {:.4f}".format(test_loss), end=', ')
        print("Std Test Loss: {:.4f}".format(np.std(test_losses)))
        print("Best Epoch: ", self.best_epoch)
        print("Best Test Accurancy: {:.4f}".format(self.best_acc))

        self.logger.info(f'Train acc per client:{train_accs}')
        self.logger.info(f'Test acc per clients: {test_accs}')

        self.logger.info("Averaged Train Accurancy: {:.4f}".format(train_acc))
        self.logger.info("Std Train Accurancy: {:.4f}".format(np.std(train_accs)))
        self.logger.info("Averaged Train Loss: {:.4f}".format(train_loss))
        self.logger.info("Std Train Loss: {:.4f}".format(np.std(train_losses)))

        self.logger.info("Averaged Test Accurancy: {:.4f}".format(test_acc))
        self.logger.info("Std Test Accurancy: {:.4f}".format(np.std(test_accs)))
        self.logger.info("Averaged Test Loss: {:.4f}".format(test_loss))
        self.logger.info("Std Test Loss: {:.4f}".format(np.std(test_losses)))
        self.logger.info(f"Best Epoch: {self.best_epoch}")
        self.logger.info("Best Test Accurancy: {:.4f}".format(self.best_acc))

        train_info = {
            'train_acc': train_acc,
            'train_loss': train_loss,
        }
        self.tensorboardLogger.add_scalars_dict(prefix='train', dic=train_info, rnd=self.epoch)

        test_info = {
            'test_acc': test_acc,
            'test_loss': test_loss,
            'best_acc': self.best_acc
        }
        self.tensorboardLogger.add_scalars_dict(prefix='test', dic=test_info, rnd=self.epoch)

    def get_global_protos(self):
        return self.global_model.get_text_prototypes()



    # def visualize_global_prototype_similarity(self):
    #     import matplotlib.pyplot as plt
    #     import seaborn as sns
    #     import matplotlib
    #     matplotlib.rcParams['pdf.fonttype'] = 42
    #
    #     self.load_model()
    #
    #     global_protos = self.get_global_protos()
    #     global_protos = global_protos / global_protos.norm(dim=-1, keepdim=True)
    #     if self.args.similarity_mode == 'cosine':
    #         similarity_matrix = global_protos @ global_protos.T
    #     elif self.args.similarity_mode == 'euclidean':
    #         similarity_matrix = torch.cdist(global_protos, global_protos, p=2)
    #     else:
    #         raise ValueError(f'Invalid similarity mode: {self.args.similarity_mode}')
    #
    #     # Convert to numpy for visualization
    #     similarity_matrix_np = similarity_matrix.detach().cpu().numpy()
    #     mask = ~np.eye(similarity_matrix_np.shape[0], dtype=bool)
    #     non_diag_elements = similarity_matrix_np[mask]
    #     min_val = non_diag_elements.min()
    #     max_val = non_diag_elements.max()
    #     normalized_values = (non_diag_elements - min_val) / (max_val - min_val)
    #     similarity_matrix_np[mask] = normalized_values
    #     print(similarity_matrix_np)
    #
    #     # Get class names from self.args.classes
    #     class_names = self.args.classes if hasattr(self.args, 'classes') else [f'Class {i}' for i in
    #                                                                            range(similarity_matrix_np.shape[0])]
    #
    #     # Plot heatmap with values
    #     plt.figure(figsize=(10, 8))
    #     if self.args.similarity_mode == 'cosine':
    #         sns.heatmap(similarity_matrix_np, annot=True, fmt=".2f", cmap='Blues', cbar=True,
    #                     xticklabels=class_names, yticklabels=class_names, vmin=0, vmax=1)
    #     else:
    #         sns.heatmap(similarity_matrix_np, annot=True, fmt=".2f", cmap='Blues', cbar=True,
    #                     xticklabels=class_names, yticklabels=class_names)
    #     plt.title('Global Prototype Similarity Heatmap')
    #     plt.xlabel('Prototypes')
    #     plt.ylabel('Prototypes')
    #     plt.xticks(rotation=45, ha='right')  # Rotate x-axis labels for better readability
    #     plt.tight_layout()  # Adjust layout to prevent label cutoff
    #     plt.show()
    #
    #     return similarity_matrix

    def Plot_TSNE_Together(self, client_num=6):
        from sklearn.manifold import TSNE
        import matplotlib
        import matplotlib.lines as mlines
        import matplotlib.pyplot as plt
        import matplotlib.markers as mmarkers
        matplotlib.rcParams['pdf.fonttype'] = 42

        self.load_model()
        all_features = []
        all_labels = []
        client_index = []

        # 为每个客户端的每个类别初始化特征总和和计数的字典
        client_category_features = {}
        client_category_counts = {}

        # 初始化用于计算所有客户端的每个类别的特征总和和计数的字典
        overall_category_features = {}
        overall_category_counts = {}

        for client in range(client_num):
            client_features, client_labels = self.clients[client].get_features_and_labels()
            # client_features = client_features / client_features.norm(dim=-1, keepdim=True)
            # client_features = client_features / np.linalg.norm(client_features, axis=-1, keepdims=True)
            all_features.append(client_features)
            all_labels.append(client_labels)
            client_index.extend([client] * len(client_labels))

            # 计算每个类别的特征总和和计数
            unique_labels = np.unique(client_labels)
            for label in unique_labels:
                label_indices = np.where(client_labels == label)
                label_features = client_features[label_indices]

                if (client, label) not in client_category_features:
                    client_category_features[(client, label)] = np.sum(label_features, axis=0)
                    client_category_counts[(client, label)] = len(label_features)
                else:
                    client_category_features[(client, label)] += np.sum(label_features, axis=0)
                    client_category_counts[(client, label)] += len(label_features)

                # 累加到总体特征总和和计数
                if label not in overall_category_features:
                    overall_category_features[label] = np.sum(label_features, axis=0)
                    overall_category_counts[label] = len(label_features)
                else:
                    overall_category_features[label] += np.sum(label_features, axis=0)
                    overall_category_counts[label] += len(label_features)

        # # 计算每个客户端每个类别的特征均值
        # client_category_means = {}
        # for key, total_features in client_category_features.items():
        #     count = client_category_counts[key]
        #     client_category_means[key] = total_features / count

        # 计算所有客户端的每个类别的特征均值
        overall_category_means = {}
        for label, total_features in overall_category_features.items():
            count = overall_category_counts[label]
            overall_category_means[label] = total_features / count

        # 记录text prototype
        over_all_text_protos = self.get_global_protos()
        over_all_text_protos /= over_all_text_protos.norm(dim=-1, keepdim=True)
        over_all_text_protos = over_all_text_protos.cpu().numpy()

        client_center = []
        feature_center = []
        text_center = []
        # # 选择输出方式显示均值（示例输出到控制台）
        # for key, mean_features in client_category_means.items():
        #     print(f"Client {key[0]}, Label {key[1]} Mean Features: {mean_features}")
        #     client_center.append(mean_features)
        # all_features.append(client_center)

        for label, mean_features in overall_category_means.items():
            print(f"Overall Mean Features for Label {label}: {mean_features}")
            feature_center.append(mean_features)

        for label, text_proto in enumerate(over_all_text_protos):
            print(f"Overall Text Prototypes for Label {label}: {text_proto}")
            text_center.append(text_proto)


        all_features.append(feature_center)
        all_features.append(text_center)

        all_features = np.concatenate(all_features, axis=0)
        all_labels = np.concatenate(all_labels, axis=0)

        tsne = TSNE(n_components=2, random_state=42)
        transformed_features = tsne.fit_transform(all_features)

        plt.figure(figsize=(8, 8))

        colors = ['OrangeRed', 'orange', 'Gold', 'Coral', 'PaleGreen', 'CornflowerBlue', 'Orchid', 'LimeGreen', 'pink',
                  'DeepSkyBlue']
        markers = [self.clients[client].marker[client] for client in range(client_num)]
        # 创建图例中的点和标记
        legend_elements = []

        # 添加颜色图例
        for idx, color in enumerate(colors):
            legend_elements.append(mlines.Line2D([0], [0], marker='o', color='w', label=f'{idx}',
                                                 markerfacecolor=color, markersize=16))

        # 添加标记图例
        for idx, marker in enumerate(markers):
            legend_elements.append(mlines.Line2D([0], [0], marker=marker, color='w', label=f'cid {idx}',
                                                 markerfacecolor='black', markersize=16))

        colormap = matplotlib.colors.ListedColormap(colors)

        # for client in range(client_num):
        #     index = np.where(np.array(client_index) == client)
        #     plt.scatter(transformed_features[index, 0], transformed_features[index, 1],
        #                 c=[colors[label] for label in all_labels[index]],
        #                 cmap=colormap, label=f'Client {client}', marker=self.clients[client].marker[client], s=25,
        #                 alpha=0.7)

        # 绘制特征中心
        features = transformed_features[len(all_labels):, :]
        # 绘制客户端中心
        index = 0
        # for key, mean_features in client_category_means.items():
        #     client, label = key
        #     plt.scatter(features[index, 0], features[index, 1], c=colors[label], cmap=colormap,
        #                 marker=self.clients[client].marker[client], s=600, alpha=1)
        #     index += 1
        # 绘制所有客户端的特征中心
        for label, mean_features in overall_category_means.items():
            plt.scatter(features[index, 0], features[index, 1], c=colors[label], cmap=colormap,
                        marker='H', s=800, alpha=1)
            index += 1

        # 绘制所有客户端的text prototype
        for label, text_proto in enumerate(over_all_text_protos):
            plt.scatter(features[index, 0], features[index, 1], c=colors[label], cmap=colormap,
                        marker='X', s=800, alpha=1)
            index += 1



        ax = plt.gca()
        ax.axes.xaxis.set_visible(False)
        ax.axes.yaxis.set_visible(False)
        for spine in ax.spines.values():
            spine.set_visible(False)

        plt.tight_layout()
        dir = self.plot_path
        if not os.path.exists(dir):
            os.makedirs(dir)

        # plt.savefig(f'{dir}/TSNE.pdf')
        plt.show()

        return





# https://github.com/yuetan031/fedproto/blob/main/lib/utils.py#L221
def proto_aggregation(local_protos_list):
    agg_protos_label = defaultdict(list)
    for local_protos in local_protos_list:
        for label in local_protos.keys():
            agg_protos_label[label].append(local_protos[label])

    for [label, proto_list] in agg_protos_label.items():
        if len(proto_list) > 1:
            proto = 0 * proto_list[0].data
            for i in proto_list:
                proto += i.data
            agg_protos_label[label] = proto / len(proto_list)
        else:
            agg_protos_label[label] = proto_list[0].data

    return agg_protos_label